apiVersion: v1
kind: Pod
metadata:
  name: mypod1 
  labels:
    app: myapp
spec:                            
  containers:
    - name: mycontainer 
      image: educafe/myimage:v1 
      livenessProbe:
        exec:
          command:
          - sh
          - -c
          - ps -ef | grep a.out
        initialDelaySeconds: 5
        periodSeconds: 10

  terminationGracePeriodSeconds: 0
   
