apiVersion: v1
kind: Pod
metadata:
  name: mypod2
  labels:
    educafe: mypod2
spec:
  containers:
  - name: nginx-container
    image: educafe/mynginx:v1
    ports:
    - containerPort: 80
      protocol: TCP

  - name: myubuntu-container
    image: educafe/myubuntu:utils
    command: ["tail"]
    args: ["-f", "/dev/null"] 
  
  terminationGracePeriodSeconds: 0


