apiVersion: v1
kind: Pod
metadata:
  name: mypod3
  labels:
    educafe: mypod3
spec:
  volumes:
  - name: shared
    emptyDir: {}    #Temporary Storage directory that is shared containers among containers in  the same pod
  containers:
  - name: read-container
    image: educafe/mynginx:v1
    volumeMounts:
      - name: shared
        mountPath: /var/www/html
  - name: write-container
    image: ubuntu
    volumeMounts:
    - name: shared
      mountPath: /web
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          echo "I am writing -- at [$(date +%T)]" > /web/index.html;
          sleep 3;
        done
        
  terminationGracePeriodSeconds: 0
      
        