apiVersion: v1
kind: Pod
metadata:
  name: env10-sp-myapp
  labels:
    educafe: sp-myapp
spec:
  containers:
  - name: myapp
    image: educafe/myapp
               
  terminationGracePeriodSeconds: 0