apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: read
        image: educafe/myread:v1
        volumeMounts:
        - name: shared
          mountPath: /app
      - name: write
        image: educafe/mywrite:v1
        volumeMounts:
        - name: shared
          mountPath: /app
     
      volumes:
      - name: shared
        hostPath:
          path: /home/educafe

      terminationGracePeriodSeconds: 0