version: "3.8"
services:
    redis:
        image: redis
        ports:
            - "80:80"
        deploy:
            replicas: 6
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.role == worker
                    # - node.role == manager
                    
                    