apiVersion: v1
kind: Service
metadata:
    name: mysvc
    labels:
        app: mc-myapp
spec:
    type: NodePort
    ports:
    -   port: 8080
        nodePort: 30080
        targetPort: 80
    selector:
        app: mc-myapp
      
      