apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels: 
    educafe: test
spec:
  containers:
  - name: nginx-container
    image: educafe/mynginx:v1
    ports:
    - containerPort: 80
      protocol: TCP
                
                