apiVersion: v1
kind: ConfigMap
metadata:
    name: myconfig-sp
data:
    nginx.conf: |-

        events {
        }

        http {
            upstream myapp {
                server 127.0.0.1:5000;
            }

            server {
                listen 80;
                location / {
                    proxy_pass         http://myapp;
                    proxy_redirect     off;
                }
            }
        }
    
    