apiVersion: v1
kind: ConfigMap
metadata:
    name: myconfig-mp
data:
    nginx.conf: |-

        events {
        }

        http {
            upstream myapp {
                # server 10.244.1.39:5000;
                server mysvc:80;
            }

            server {
                listen 80;
                location / {
                    proxy_pass         http://myapp;
                    proxy_redirect     off;
                }
            }
        }
    
    