apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
spec:
  type: NodePort
  clusterIP: 10.96.1.100
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30010
    targetPort: 80
  selector:
    run: mynginx

