apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-sp-proxy-config
data:
    nginx.conf: |-

        events {
        }

        http {
            upstream myapp {
                # server 10.244.2.45:5000;
                server svc-backend-sp:80;
            }

            server {
                listen 80;
                location / {
                    proxy_pass         http://myapp;
                    proxy_redirect     off;
                }
            }
        }
    

      