apiVersion: v1
kind: ConfigMap
metadata:
    name: myconfig
data:
    nginx.conf: |-

        events {
        }

        http {
            upstream myapp {
                server 10.244.1.13:5000;
            }

            server {
                listen 80;
                location / {
                    proxy_pass         http://myapp;
                    proxy_redirect     off;
                }
            }
        }
    

      