apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
      - name: job
        image: busybox
        command: ['sh', '-c', 'echo "Hello, Kubernetes!"']
      restartPolicy: OnFailure

